version: '3.7'
services:
  temporary-apache:
    container_name: 'temporary-apache'
    image: arm64v8/php:7.2-apache
    ports:
      - "80:80"
    volumes:
      - ./apache:/etc/apache2/sites-available/
      - ./html:/var/www/html/
    networks:
      - docker-network
      
networks:
  docker-network:
  
    driver: bridge


  